### ISSUE TITLE
Explicit Tag in Feed

### ISSUE THREAD

**Issue by obstschale** [Dicentis/dicentis#17]

**Comment by Damian-Kite** [comment]
Danke für das tolle Plugin. 
Da der explicit Tag im Feed fehlt, kann der nicht mehr in iTunes eingereicht werden.

**Comment by obstschale** [comment]
Danke @Damian-Kite für die Meldung. Ich werde noch diese Woche einen Patch erstellen, der das fixt :) Falls du noch mehr Bugs findest einfach melden.

**Comment by Damian-Kite** [comment]
Vielen Dank @obstschale schale für die schnelle Reaktion - werde den fix gern testen

**Comment by obstschale** [comment]
Also bei mir hat es geklappt :) Konnte meinen neuen Podcast in iTunes einreichen. Hatte allerdings ein paar Probleme mit HTTPS. Also wenn du HTTPS einsetzt kann es vermutlich nicht klappen, da iTunes keine HTTPS Feeds annimmt.
