### ISSUE TITLE
Selecting Series.

### ISSUE THREAD

**Issue by AgencyDev** [Dicentis/dicentis#24]
I can't select previous series that i posted on the podcast.

example : http://www.icf-leiden.com/podcast/

**Comment by obstschale** [comment]
That is weird. I will take a look at this. Thx for reporting this.

**Comment by AgencyDev** [comment]
No problem, and thanks for having a look at it.

**Comment by obstschale** [comment]
@AgencyDev I just took another look at your site and it seems to work. Can you confirm that?

**Comment by AgencyDev** [comment]
Hello it indeed seems to work again, thanks!

Date: Wed, 29 Jul 2015 07:55:19 -0700

**Comment by obstschale** [comment]
Great to hear. Though don't thank me. I didn't do anything ^^
