### ISSUE TITLE
Check Backend on https

### ISSUE THREAD

**Issue by noelboss** [Dicentis/dicentis#25]
Please check the plugin on any http links, this breaks backends forced over https. For me, the plugin icon is not shown in the backend next to the podcast section, think this has to do with https. There are probably other occurrences. Search fro http:// and replace with // to make things protocol agnostic.

Be blessed and thanks for your great work!

**Comment by obstschale** [comment]
I will take a look at this. Is it only the icon?

**Comment by obstschale** [comment]
I found the bug. Thx for reporting. The fix will come with the next update soon.

**Comment by noelboss** [comment]
Since this is a critical and breaking issue, could you release it now?
