### ISSUE TITLE
Package on wp.org still includes TGMPA

### ISSUE THREAD

**Issue by jrfnl** [Dicentis/dicentis#29]
Hiya,

I noticed that the plugin as published on wp.org still contains the TGMPA library while it seems you are no longer using it.

If you *are* using it, please upgrade it to the latest version.

If you are not, you may want to consider removing the file on wp.org.

Smile,
The TGMPA team.

**Comment by obstschale** [comment]
Hey @jrfnl, thx for your issue. I'm sorry that my answer is coming late, but Christmas time is keeping me busy :santa: 

I already did remove TGM from my plugin in commit 9f5a63bd87b83952a6e131c596ad10e73c101afc. Did you find another place where I referenced it in my plugin, which I missed to remove?

**Comment by jrfnl** [comment]
As i stated in my original message - the files haven't been removed from the plugin on **wp.org**.

https://plugins.trac.wordpress.org/browser/dicentis-podcast/trunk/includes/libraries
https://plugins.trac.wordpress.org/browser/dicentis-podcast/tags/0.2.5/includes/libraries

**Comment by obstschale** [comment]
Oh I see. I missunderstood your message. Thx for the hint. I'll remove them from the SVN.

**Comment by jrfnl** [comment]
Thanks ;-)
