### ISSUE TITLE
Podcast Archiv darstellen

### ISSUE THREAD

**Issue by supertoub** [Dicentis/dicentis#39]
Gibt es die Möglichkeit ein Podcast Archiv darzustellen und wenn ja wie?
Wie wird das hier gemacht https://www.icf.ch/podcast/ ist das Teil von dicentis oder ein anderes Plugin?

**Comment by obstschale** [comment]
Ich verfolge die Entwicklung der ICF Seite nicht mehr, daher kenne ich nicht mehr die genauen Details. Aber was ich von vor paar Jahren noch weiß ist, dass die Daten vom Dicentis Plugin verwaltet werden aber das Frontend ist custom. Also im Theme programmiert. Das Theme holt sich lediglich die nötigen Daten mittels WordPress Methoden und stellt sie dar.

Mehr kann ich dir leider nicht sagen.

**Comment by supertoub** [comment]
super vielen dank für deine Antwoer
