### ISSUE TITLE
pdf files not visible

### ISSUE THREAD

**Issue by SabiKottmann** [Dicentis/dicentis#40]
Hey, after Update my pdf files are hidden. Any idea how to make them visible again?

For each Podcast i have an audio, video and pdf file on our website. Audio and Video are available, pdf not anymore.

Br, Sabrina

**Comment by obstschale** [comment]
I"m sorry to hear that. Unfortunately, I stopped working on dicentis. I will archive this Repo soon and add a note to the readme.
